type AutoGenerated []struct {
	BaseModel
	// These are properties from the MITRE ATT&CK json
	ObjectMarkingRefs  []string `json:"object_marking_refs"`
	CreatedByRef       string   `json:"created_by_ref"`
	ExternalReferences []struct {
		ExternalID string `json:"external_id"`
		URL        string `json:"url"`
		SourceName string `json:"source_name"`
	} `json:"external_references"`
	Description             string `json:"description"`
	XMitreAttackSpecVersion string `json:"x_mitre_attack_spec_version"`
	XMitreModifiedByRef     string `json:"x_mitre_modified_by_ref"`
	XMitreShortname         string `json:"x_mitre_shortname"`
}